/**
 * WhatsApp Daily Report Service
 * Handles sending daily vehicle reports via WhatsApp
 */

import { whatsappService } from './whatsapp-service'
import { createAdminClient } from './supabase/admin'
import { generateDailyReportPDF, VehicleReportData } from './pdf-service'

export interface DailyReportWhatsAppData {
  managerName: string
  managerPhone: string
  reportDate: string
  nextDayCount: number
  pendingCount: number
  pdfBuffer: Buffer
  tenantName?: string
}

/**
 * Send daily vehicle report via WhatsApp with PDF attachment
 */
export async function sendDailyReportViaWhatsApp(
  data: DailyReportWhatsAppData,
  tenantId?: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const supabase = createAdminClient()
    
    // Load WhatsApp configuration for the tenant (with fallback to global config)
    let config = await whatsappService.loadConfig(supabase, tenantId)
    
    // If tenant-specific config not found, try global config (null tenant_id)
    if (!config && tenantId) {
      console.log(`[Tenant: ${tenantId}] Tenant-specific WhatsApp config not found, trying global config...`)
      config = await whatsappService.loadConfig(supabase, null)
    }
    
    if (!config || !config.enabled) {
      const errorMsg = tenantId 
        ? `WhatsApp notifications are not enabled for tenant ${tenantId} (and no global config found)`
        : 'WhatsApp notifications are not enabled'
      console.warn(`⚠️ ${errorMsg}`)
      return { success: false, error: errorMsg }
    }
    
    // Verify required config fields
    if (config.provider === 'messageautosender' && (!config.apiKey || !config.userId || !config.password)) {
      const errorMsg = 'WhatsApp configuration incomplete: Missing API key, user ID, or password'
      console.warn(`⚠️ ${errorMsg}`)
      return { success: false, error: errorMsg }
    }

    // Generate message text
    const totalVehicles = data.nextDayCount + data.pendingCount
    const message = generateWhatsAppMessage(data, totalVehicles)

    // Send message with PDF document
    const result = await whatsappService.sendDocument(
      data.managerPhone,
      message,
      data.pdfBuffer,
      `daily-vehicle-report-${data.reportDate.replace(/\//g, '-')}.pdf`
    )

    return result
  } catch (error: any) {
    console.error('Error sending daily report via WhatsApp:', error)
    return { success: false, error: error.message || 'Failed to send WhatsApp report' }
  }
}

/**
 * Generate WhatsApp message text for daily report
 */
function generateWhatsAppMessage(data: DailyReportWhatsAppData, totalVehicles: number): string {
  let message = `📋 *Daily Vehicle Report - ${data.reportDate}*\n\n`
  message += `Hello ${data.managerName},\n\n`
  
  if (data.tenantName) {
    message += `*Tenant:* ${data.tenantName}\n\n`
  }

  message += `*Report Summary:*\n`
  message += `📅 Vehicles for Tomorrow: *${data.nextDayCount}*\n`
  message += `⏳ Pending Vehicles: *${data.pendingCount}*\n`
  message += `📊 Total: *${totalVehicles}*\n\n`

  if (totalVehicles > 0) {
    message += `A detailed PDF report has been attached with complete vehicle information including:\n`
    message += `• Customer details\n`
    message += `• Vehicle specifications\n`
    message += `• Status and priority\n`
    message += `• Issues reported\n`
    message += `• Accessories requested\n`
    message += `• Estimated costs\n\n`
  } else {
    message += `No vehicles require immediate attention today.\n\n`
  }

  message += `_Generated by ZORAVO OMS_`

  return message
}

/**
 * Get phone number for a manager/coordinator
 * Tries notification_preferences first (with tenant context), then profiles table
 */
export async function getManagerPhoneNumber(
  userId: string,
  tenantId?: string
): Promise<string | null> {
  try {
    const supabase = createAdminClient()

    // First try notification_preferences table with tenant context
    let query = supabase
      .from('notification_preferences')
      .select('phone_number')
      .eq('user_id', userId)
      .eq('whatsapp_enabled', true)
      .not('phone_number', 'is', null)
    
    // Add tenant filter if tenantId is provided
    if (tenantId) {
      query = query.eq('tenant_id', tenantId)
    }
    
    query = query.limit(1)

    const { data: prefs, error: prefsError } = await query

    if (!prefsError && prefs && prefs.length > 0 && prefs[0].phone_number) {
      const phone = prefs[0].phone_number.trim()
      // Ensure phone number has country code
      if (phone && phone.length >= 10) {
        return phone.startsWith('+') ? phone : `+91${phone.replace(/^91/, '').replace(/^0/, '')}`
      }
      return phone
    }

    // Fallback: try profiles table (if it has phone field)
    const { data: profile, error: profileError } = await supabase
      .from('profiles')
      .select('phone')
      .eq('id', userId)
      .limit(1)
      .maybeSingle()

    if (!profileError && profile && profile.phone) {
      const phone = profile.phone.trim()
      // Ensure phone number has country code
      if (phone && phone.length >= 10) {
        return phone.startsWith('+') ? phone : `+91${phone.replace(/^91/, '').replace(/^0/, '')}`
      }
      return phone
    }

    return null
  } catch (error) {
    console.error('Error getting manager phone number:', error)
    return null
  }
}

